.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. flocoin_qt test_flocoin_qt
clean: FORCE
	$(MAKE) -C .. flocoin_qt_clean test_flocoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_flocoin_qt_check
flocoin-qt flocoin-qt.exe: FORCE
	 $(MAKE) -C .. flocoin_qt
apk: FORCE
	$(MAKE) -C .. flocoin_qt_apk
